apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
  annotations:
    policies.kyverno.io/title: Verify Container Image Crypto Signature
    policies.kyverno.io/category: Custom Policy
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.11.0
    kyverno.io/kyverno-version: 1.11.0
    kyverno.io/kubernetes-version: "1.26-1.29"
    policies.kyverno.io/description: >-
      This policy ensures the Pod referenced container image is signed by KMS with Cosign format.
      The container registry should have an entry for the Cosign signature for this check to pass.
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-img
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "282527170177.dkr.ecr.us-east-1.amazonaws.com/*"
        skipImageReferences:
        - "ghcr.io/*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4d8EIJHcmGY6ydTHj0kf
                MxxHfiTEixYh41fSG+ZcEX8pQjZ/d5M8+5gzcUdNdCBfwCU+8Crc8+fNf3Ey/JIk
                MtD5ad9uTP9eELJZ1FJgUtVCoMZwsR4SQ7q1mqwxOj+e5Y6OmYLqfM9NSRXzUqT5
                JSd4W/Mm06BNwhrLHOZyKS1rzvckb7jidCrNbL0A9KSZD/QeWuol8wb5SO0hMdZM
                42QTNtNGixwl66pUgpBknryHjXtdQBti/fpxYRMn5+F+Gf6CT81civIg0E9pej2E
                Ansk8NlQRIuzi/g2Sb6PgH1QcfM7jxthXLXBDbNyxZ6wI32escniDMpcM76bhNNw
                kn2Et8F39RkFVCTDNGJJteb2iwZabIEPExnpx+lKx0riytykznEwsOCVNJJbLggY
                ZJdvviKTMRuFmn09WMYTc9dUjR3RiTN0p+j6wWhaDO6iU94Lff62mbkJEwpLfAce
                b/+LIZhxc2vKz9ADmb939LeIOnMFjfODF9ah03dAfcLRM9RPjmYY4SEHUZMUFh7W
                eLRe7e6Mpi69a4BJhh50Tf18UFwgLVqOJBwwzXUVG9YZ722I8ucJDqFCpHNlkOYY
                o3Wmu4Dc5slV9GGB1toIdJbe5QNYtJimhY4SNwWMnRuwT53rdzuhOLIlX22+pey/
                pQD8CdvkBjc9Bevkr94SahECAwEAAQ==
                -----END PUBLIC KEY-----
              rekor:
                ignoreTlog: true
#               url: https://rekor.sigstore.dev
